id: I909D5A9A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T14:29:07+00:00'
last_modified: '2022-06-15T17:43:12.661412+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21849
  title: འགྲོ་བ་བཟང་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    66DC:
      image_group_id: I1KG23002
      title: Volume 1 of 'gro ba bzang mo/
      total_pages: 134
      order: 1
      base_file: 66DC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
